<?php

function custom_menu_attributes_entity_base_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'menu_link_content') {
    $fields['link']->setDisplayOptions('form', [
      'type' => 'link_attributes',
      'weight' => -2,
      'settings' => [
        'enabled_attributes' => [
          'id' => TRUE,
          'name' => FALSE,
          'target' => TRUE,
          'rel' => TRUE,
          'class' => TRUE,
          'accesskey' => FALSE,
          'data-medawar' => TRUE
        ],
      ],
    ]);
  }
}
