<?php


/**
 * Getter to return the share buttons.
 */
function addtoany_field_get_share_buttons($node) {
  return  '<div class="addtoany-links">' . addtoany_create_node_buttons($node) . '</div>';
}

/*
* Implements hook_entity_info_alter().
*/
function addtoany_field_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['addtoany'] = array(
    'label' => t('Add to Any'),
    'custom settings' => FALSE,
  );
}


/**
 * Implements hook_field_extra_fields().
 */
function addtoany_field_field_extra_fields() {
  // $extra = array('node' => array());
  $extra = array();

  // foreach (node_type_get_types() as $type => $type_info) {
    // if ($type == 'community_event') {
      $extra['node']['community_event']['display'] = array(
        'addtoany_field' => array(
          'label' => t('Add to Any'),
          'description' => t('Share links'),
          'weight' => 0,
          'visible' => FALSE,
        ),
      );
    // }
 //  }

  return $extra;
}

/**
 * Implements hook_node_load().
 */
function addtoany_field_node_load($nodes, $types) {
  if (!in_array('community_event', $types)) {
    return;
  }

  foreach ($nodes as $node) {
    // add the project number to each node
    $node->addtoany_field = addtoany_field_get_share_buttons($node);
  }

  // foreach ($nodes as $node) {
  //   // add the project number to each node
  //   $node->addtoany_field = array(
  //     '#prefix' => '<div class="addtoany-links">',
  //     '#suffix' => '</div>',
  //     '#markup' => addtoany_create_node_buttons($node),
  //   );
  // }
}

// /**
//  * Implements hook_node_view().
//  */
// function addtoany_field_node_view($node, $view_mode, $langcode) {
//   $content = &$node->content;

//   if ($node->type == 'community_event') {
//     $content['addtoany_field'] = array(
//       '#prefix' => '<div class="addtoany-links">',
//       '#suffix' => '</div>',
//       '#markup' => addtoany_create_node_buttons($node),
//     );
//   }

// }

/**
 * Implements hook_entity_property_info_alter().
 *
 * Note: This hook is provided by Entity API.
 */
function addtoany_field_entity_property_info_alter(&$info) {
  $info['node']['bundles']['community_event']['properties']['addtoany_field'] = array(
    'type' => 'text',
    'label' => t('Share buttons'),
    'sanitized' => TRUE,
    'getter callback' => 'addtoany_field_get_share_buttons',
  );
}

/**
 * Implements hook_views_data_alter().
 *
 * Note: This hook is provided by Views.
 */
function addtoany_field_views_data_alter(&$data){
  // Entity API seems to add a handler, but at a different place.
  $data['node']['addtoany_field'] = $data['entity_node']['addtoany_field'];
}
